//! Generates `src/circuit/fixed_bases_generated.rs`: the windowed tables the ECC chip needs for
//! every fixed base the action circuit multiplies. Orchard ships the same kind of constants;
//! searching them at runtime costs minutes single threaded.
//!
//! `cargo run --release --example gen_fixed_bases > src/circuit/fixed_bases_generated.rs`

use ff::PrimeField;
use group::{Curve, GroupEncoding};
use halo2_gadgets::ecc::chip::{find_zs_and_us, H, NUM_WINDOWS, NUM_WINDOWS_SHORT};
use pasta_curves::pallas;

use gradido_blockchain_zk::signature::{randomness_base, spend_auth_base, value_base};

fn emit(name: &str, base: pallas::Point, windows: usize) {
    let affine = base.to_affine();
    let tables = find_zs_and_us(affine, windows).expect("tables exist");
    println!("pub const {name}_POINT: [u8; 32] = {:?};", affine.to_bytes());
    print!("pub const {name}_Z: [u64; {windows}] = [");
    for (z, _) in &tables {
        print!("{z},");
    }
    println!("];");
    println!("pub const {name}_U: [[[u8; 32]; {H}]; {windows}] = [");
    for (_, us) in &tables {
        print!("    [");
        for u in us.iter() {
            print!("{:?},", u.to_repr());
        }
        println!("],");
    }
    println!("];");
}

fn main() {
    println!("// Generated by examples/gen_fixed_bases.rs — do not edit by hand.");
    println!("// Window tables for the fixed bases of the action circuit, see circuit::action_slice.");
    println!("#![allow(clippy::all)]");
    emit("VALUE_V", value_base(), NUM_WINDOWS_SHORT);
    emit("RANDOMNESS_R", randomness_base(), NUM_WINDOWS);
    emit("SPEND_AUTH_G", spend_auth_base(), NUM_WINDOWS);
}
